/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_NativeExample */

#ifndef _Included_JNI_NativeExample
#define _Included_JNI_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_NativeExample
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_NativeExample_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
